"""classes

Revision ID: d03f19a5a453
Revises: a1efa85a0371
Create Date: 2018-10-23 10:16:39.784355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03f19a5a453'
down_revision = 'a1efa85a0371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('topics', sa.String(length=64), nullable=True),
    sa.Column('topicsNext', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.String(length=64), nullable=True),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'training', sa.Column('finalizada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'training', 'finalizada')
    op.drop_table('class')
    # ### end Alembic commands ###
